- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/config/SecurityConfig.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/entity/Users.java
- DB 접근을 위한 Security 설정 구현
- Users 파일 위치 조정
> Feat: Spring Security 초기 구현

- Hana_Bridge_BE-API/bin/main/application.yml
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/controller/BoardApiController.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/dto/board/BoardAddRequest.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/dto/board/BoardResponse.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/dto/board/BoardUpdateRequest.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/entity/Board.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/repository/BoardRepository.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/service/BoardService.java
- Hana_Bridge_BE-API/src/main/resources/application.yml
Code게시판, Notice게시판의 등록, 조회, 수정, 삭제
주의: userId는 일반 컬럼으로 선언 (추후에 FK로 선언)
> Feat: Board 게시판 API 기능 구현

- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/dto/error/ErrorResponse.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/errorhandler/GlobalExceptionHandler.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/service/AssembleBoardService.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/service/BoardService.java
- 에러 코드, 메세지 전달하는 dto 작성
- 에러별로 정리하여 처리하는 global Exception Handler 구현
- Service 코드에 예외 추가
>  Feat: global exception handler 구현

- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/controller/BoardApiController.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/dto/board/BoardResponse.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/dto/comment/CommentAddRequest.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/dto/comment/CommentResponse.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/dto/comment/CommentUpdateRequest.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/entity/Board.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/entity/Comment.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/repository/CommentRepository.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/service/BoardService.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/service/CommentService.java
- 댓글 등록, 전체 조회, 수정, 삭제 API 기능 구현
- BoardAPIController에 함께 작성
> Feat: Board Commit API 기능 구현

- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/controller/BoardApiController.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/dto/board/BoardResponse.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/dto/board/GoodAddRequest.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/entity/Good.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/repository/GoodRepository.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/service/GoodService.java
- Board Dto  수정
- 좋아요 생성, 삭제는 주석으로 중간 비워져있습니다.
> Feat/21: code 게시판 좋아요 API 구현 

- Hana_Bridge_FE-Cli/src/App.css
- Hana_Bridge_FE-Cli/src/App.jsx
- Hana_Bridge_FE-Cli/src/clientView/Header.jsx
- Hana_Bridge_FE-Cli/src/clientView/MainBoard.jsx
- Hana_Bridge_FE-Cli/src/clientView/board/AddBoard.jsx
- Hana_Bridge_FE-Cli/src/clientView/board/DetailBoard.jsx
- Hana_Bridge_FE-Cli/src/clientView/login/Login.jsx
- Hana_Bridge_FE-Cli/src/clientView/login/SignUp.jsx
- Hana_Bridge_FE-Cli/src/service/ApiClient.jsx
- Hana_Bridge_FE-Cli/src/store/userSlice.js
> Feat: front 화면 구성 및 API연결

- Hana_Bridge_FE-Cli/package-lock.json
- Hana_Bridge_FE-Cli/package.json
- Hana_Bridge_FE-Cli/src/App.jsx
- Hana_Bridge_FE-Cli/src/clientView/MainBoard.jsx
- Hana_Bridge_FE-Cli/src/clientView/board/AssembleBoard.jsx
- Hana_Bridge_FE-Cli/src/clientView/board/CodeBoard.jsx
- Hana_Bridge_FE-Cli/src/clientView/board/DetailAssemble.jsx
- Hana_Bridge_FE-Cli/src/clientView/board/DetailBoard.jsx
- Hana_Bridge_FE-Cli/src/clientView/board/NoticeBoard.jsx
- Hana_Bridge_FE-Cli/src/service/ApiClient.jsx
MainBoard => NoticeBoard, CodeBoard, AssembleBoard
DetailBoard => DetailBoard, DetailAssemble
> Feat: 컴포넌트 분리

- Hana_Bridge_FE-Cli/src/clientView/board/AddBoard.jsx
- Hana_Bridge_FE-Cli/src/clientView/board/AddComment.jsx
- Hana_Bridge_FE-Cli/src/clientView/board/Comments.jsx
- Hana_Bridge_FE-Cli/src/clientView/board/DetailAssemble.jsx
- Hana_Bridge_FE-Cli/src/clientView/board/DetailBoard.jsx
- Hana_Bridge_FE-Cli/src/service/ApiClient.jsx
> Feat: 댓글 기능 추가

- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/controller/BoardApiController.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/dto/board/BoardResponse.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/dto/board/GoodResponse.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/service/GoodService.java
- 좋아요 여부 BoardResponse에 추가 처음 렌더링 시에
- 좋아요 등록, 삭제시에 좋아요 누른 여부, 갯수를 리턴
> Feat: 좋아요 여부 확인 변수, 좋아요 여부 확인 기능 추가

- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/controller/UsersApiController.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/dto/assemble/AssembleBoardResponse.java
> Fix: assembleBoardResponse에서 goodCount -> likeCount 변경

- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/config/OpenAiConfig.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/controller/BoardApiController.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/controller/CustomBotController.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/dto/openAi/ChatGPTRequest.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/dto/openAi/ChatGPTResponse.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/dto/openAi/Message.java
> Refactor: BoardApiController 수정

- Hana_Bridge_BE-API/build.gradle
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/config/openai/OpenAiConfig.java
> Feat: OpenAI config 환경설정 구현

- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/dto/openAi/ChatGPTRequest.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/dto/openAi/ChatGPTResponse.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/dto/openAi/Message.java
> Rename: dto.openAi 패키지명 수정 -> openai

- Hana_Bridge_FE-Cli/package-lock.json
- Hana_Bridge_FE-Cli/package.json
- Hana_Bridge_FE-Cli/src/clientView/AIchat/AIChat.jsx
AI 답변 마크다운 적용 & 글씨 왼쪽 정렬 & 코드 뷰어 적용
> ✨ Feat: AI 답변 마크다운 적용 & 글씨 왼쪽 정렬 & 코드 뷰어 적용

- Hana_Bridge_FE-Cli/src/clientView/AIchat/AIChat.jsx
> 📝 Comment: AIChat (주석 추가)

- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/controller/BoardApiController.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/dto/board/BoardResponse.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/repository/CommentRepository.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/service/CommentService.java
- dto에 댓글 갯수 countComment 필드 추가
- controller에서 게시글 전체 조회, 상세보기 시에 댓글 갯수 추가
> Feat : 댓글 갯수 반환 API 추가

- Hana_Bridge_FE-Cli/src/App.jsx
- Hana_Bridge_FE-Cli/src/clientView/board/AddBoard.jsx
- Hana_Bridge_FE-Cli/src/clientView/board/AddComment.jsx
- Hana_Bridge_FE-Cli/src/clientView/board/AssembleBoard.jsx
- Hana_Bridge_FE-Cli/src/clientView/board/CodeBoard.jsx
- Hana_Bridge_FE-Cli/src/clientView/board/Comments.jsx
- Hana_Bridge_FE-Cli/src/clientView/board/DetailAssemble.jsx
- Hana_Bridge_FE-Cli/src/clientView/board/DetailBoard.jsx
- Hana_Bridge_FE-Cli/src/clientView/board/NoticeBoard.jsx
- Hana_Bridge_FE-Cli/src/clientView/error/NotFound.jsx
- Hana_Bridge_FE-Cli/src/service/ApiClient.jsx
fetch 함수 Backend에서 보내는 에러 확인&페이지 이동 + error 틀 생성
> Refactor; fetch 함수 Backend에서 보내는 에러 확인(board 폴더)

- Hana_Bridge_FE-Cli/src/App.css
- Hana_Bridge_FE-Cli/src/clientView/AIchat/AIChat.jsx
- Hana_Bridge_FE-Cli/src/clientView/CodeHelper.jsx
- Hana_Bridge_FE-Cli/src/clientView/header/AiRightHeader.jsx
- Hana_Bridge_FE-Cli/src/clientView/header/RightHeader.jsx
- Hana_Bridge_FE-Cli/src/service/ApiClient.jsx
- Hana_Bridge_FE-Cli/tailwind.config.js
- AiChat 화면에선 전용 rightheader 추가
> Feat: Right Header 게시글 목록 구현

- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/config/WebSecurityConfig.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/controller/OpenAiApiController.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/dto/openai/ChatGPTRequest.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/service/OpenAiService.java
- Hana_Bridge_FE-Cli/src/clientView/AIchat/AIChat.jsx
- Hana_Bridge_FE-Cli/src/clientView/board/DetailAssemble.jsx
- Hana_Bridge_FE-Cli/src/clientView/header/AiRightHeader.jsx
- Hana_Bridge_FE-Cli/src/service/ApiClient.jsx
> Test: OpenAI 답변 스트리밍 형태로 받기

- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/repository/AssembleRepository.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/repository/BoardRepository.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/service/AssembleBoardService.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/service/BoardService.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/service/TokenService.java
> Refactor: 게시글 조회 최근 생성한 시간 순으로 정렬하여 가져오기

- Hana_Bridge_FE-Cli/src/clientView/board/AssembleBoard.jsx
- Hana_Bridge_FE-Cli/src/clientView/board/CodeBoard.jsx
- Hana_Bridge_FE-Cli/src/clientView/board/NoticeBoard.jsx
- Hana_Bridge_FE-Cli/src/clientView/header/LeftHeader.jsx
- Hana_Bridge_FE-Cli/src/style/CommonBoardStyle.jsx
- Hana_Bridge_FE-Cli/src/style/CommonFrame.jsx
- Hana_Bridge_FE-Cli/src/style/CommonLeftStyle.jsx
> Feat: Code게시판 세부 디자인 클래스명 조합 정리

- Hana_Bridge_FE-Cli/src/clientView/Home.jsx
- Hana_Bridge_FE-Cli/src/clientView/header/Header.jsx
- Hana_Bridge_FE-Cli/src/service/useScrollSnap.js
- Hana_Bridge_FE-Cli/src/style/CommonFrame.jsx
- Hana_Bridge_FE-Cli/src/style/CommonHomeStyle.jsx
- Hana_Bridge_FE-Cli/src/style/CommonStyle.jsx
- home 공통 디자인
- 상단 헤더 애니메이션 제거
> Feat: 홈화면 애니메이션 속도 조절

- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/controller/BoardApiController.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/repository/BoardRepository.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/service/BoardService.java
- Hana_Bridge_FE-Cli/src/clientView/board/CodeBoard.jsx
- Hana_Bridge_FE-Cli/src/clientView/board/MyBoard.jsx
- Hana_Bridge_FE-Cli/src/clientView/board/NoticeBoard.jsx
- Hana_Bridge_FE-Cli/src/service/ApiClient.jsx
- Hana_Bridge_FE-Cli/src/style/CommonBoardStyle.jsx
- API 구현
- code, notic, my 보드에 연결 완료
> Feat: Boards 검색 API 구현, 연결

- Hana_Bridge_FE-Cli/src/clientView/AIchat/AIChat.jsx
- Hana_Bridge_FE-Cli/src/clientView/dashboard/DashBoardCards.jsx
> Refactor/385 - AiChat 화면 수정

- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/dto/assemble/AssembleBoardResponse.java
> Refactor: 좋아요, 댓글 수 카운트 기본값 지정

- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/controller/AssembleApiController.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/controller/BoardApiController.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/controller/OpenAiApiController.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/dto/assemble/AssembleAddRequest.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/dto/openai/SummaryResponse.java
> Refactor: 자동 포스팅 로직 수정

- docker-compose.yml
> Feat: zabbix 모니터링 도구 추가

- Hana_Bridge_FE-Cli/package-lock.json
- Hana_Bridge_FE-Cli/package.json
- Hana_Bridge_FE-Cli/src/clientView/header/Header.jsx
- Hana_Bridge_FE-Cli/src/clientView/user/LoginModal.jsx
Reverts junhaha1/Hana_Bridge_Project#433
> Revert "회원가입 이동 부분 주석 처리 (Header, LoginModal)"

- Backend_Monitor/build.gradle
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/config/WebConfiguration.java
> Feat: 서비스 서버에 배포

- Hana_Bridge_BE-API/build.gradle
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/config/WebSecurityConfig.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/config/jwt/TokenProvider.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/controller/AuthApiController.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/service/EmailAuthService.java
- Hana_Bridge_BE-API/src/main/java/com/adela/hana_bridge_beapi/service/EmailService.java
- Hana_Bridge_BE-API/src/main/resources/application.yml
- 인증 코드 토큰 발급 구현
- 이메일 uri 연결
- 인증 로직 구현
> Feat: 이메일 인증 기능 구현

- Hana_Bridge_FE-Cli/src/App.css
- Hana_Bridge_FE-Cli/src/App.jsx
- Hana_Bridge_FE-Cli/src/clientView/AIchat/AIChat.jsx
- Hana_Bridge_FE-Cli/src/clientView/board/AssembleBoard.jsx
- Hana_Bridge_FE-Cli/src/clientView/board/CodeBoard.jsx
- Hana_Bridge_FE-Cli/src/clientView/board/DetailAssemble.jsx
- Hana_Bridge_FE-Cli/src/clientView/board/DetailBoard.jsx
- Hana_Bridge_FE-Cli/src/clientView/board/MyBoard.jsx
- Hana_Bridge_FE-Cli/src/clientView/board/NoticeBoard.jsx
- Hana_Bridge_FE-Cli/src/style/CommentStyle.jsx
- Hana_Bridge_FE-Cli/src/style/CommonDetail.jsx
- Hana_Bridge_FE-Cli/src/style/CommonFrame.jsx
- Hana_Bridge_FE-Cli/src/style/CommonStyle.jsx
> Refactor/485 - front 수정

- docker-compose.yml
> Feat: dev -> main 병합하여 서비스 서버에 배포

- Hana_Bridge_FE-Cli/src/clientView/header/LeftHeader.jsx
> Fix: Front 버그 수정
